#include "GLOBALS.h"

QString GLOBALS::INTERFACE;
int GLOBALS::SEND_RATE = 512;
int GLOBALS::BRUTEFORCE_FACTOR = 2;
int GLOBALS::AUTH_PACK_BURST = 1;
int GLOBALS::AUTH_RETRIES = 10;
int GLOBALS::BROADCAST_MIN_PACKET = 68;
int GLOBALS::CHOP_MIN_PACKET = 68;
int GLOBALS::FRAG_MIN_PACKET = 68;
int GLOBALS::BROADCAST_MAX_PACKET = 128;
int GLOBALS::CHOP_MAX_PACKET = 128;
int GLOBALS::FRAG_MAX_PACKET = 150;


